version: '3.9'
networks:
   social:
     driver: bridge

services:
  nginx:
    build:
      context: ./nginx/
      args:
        http_protocol: ${HTTP_PROTOCOL}
        server_name: ${HOSTNAME}
    restart: always
    environment:
      SERVICE_TAGS: ${TAG}
    links:
      - php
    ports:
      - '${API_HTTP_PORT}:80'
    volumes:
      - ./volumes/backend:/var/www/
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/nginx_main.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - social

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${TAG}
      SERVICE_NAME: mysql
    networks:
      - social

  php:
    build:
      context: ./php/
    restart: always
    environment:
      SERVICE_TAGS: ${TAG}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '${PORT_PHP}:9000'
    volumes:
      - ../project/app:/var/www
      - ./php/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
    networks:
      - social