version: '3.7'

networks:
  social:
    driver: bridge

services:
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "8061:8061"
      - "8062:8062"
      - "8063:8063"
    depends_on:
      - auth-service
      - post-service
      - user-service
    networks:
      - social

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - social

  redis:
    image: redis:6.0
    networks:
      - social

  auth-service:
    build:
      context: ../project/auth-service
      dockerfile: Dockerfile
    volumes:
      - ../project/auth-service:/var/www
    networks:
      - social

  post-service:
    build:
      context: ../project/post-service
      dockerfile: Dockerfile
    ports:
      - "8060:9000"
    volumes:
      - ../project/post-service:/var/www
    networks:
      - social

  user-service:
    build:
      context: ../project/user-service
      dockerfile: Dockerfile
    volumes:
      - ../project/user-service:/var/www
    networks:
      - social

volumes:
  db-data:
