version: '3.7'

networks:
  social:
    driver: bridge

services:
  nginx-service:
    image: nginx:1.25.1-alpine3.17
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${API_HTTP_PORT}:80"
    networks:
      - social

  redis-service:
    image: redis:7.2-rc-alpine3.18
    restart: always
    environment:
      SERVICE_TAGS: ${TAG}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - social
